FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ["package*.json", "yarn.lock*", "./"]

RUN npm install --global yarn nodemon --force
RUN yarn install --force --silent

# Bundle app source
COPY . .

EXPOSE 8000
CMD [ "nodemon", "app" ]