name: Docker Image CI

on:
  workflow_call:
    secrets:
      PERSONAL_TOKEN:
        required: true
      USERNAME:
        required: true

jobs:
  build-and-push:
    name: Build Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PERSONAL_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: api/
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
